version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '127.0.0.1:3901:3901'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
